name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [retrain]

env:
  AWS_REGION: eu-west-1
  ROLE_ARN: arn:aws:iam::709598629349:role/Github-actions-mlops-For-Me

jobs:
 
  # JOB 1 — AUTO
 
  validate-and-plan:
    name: Format + Validate + Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var="slack_webhook_url=${{ secrets.SLACK_WEBHOOK_URL }}" -var="github_token=${{ secrets.GITHUB_TOKEN_DRIFT }}"

 
  # JOB 2 — MANUAL APPLY
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: validate-and-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production       

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="slack_webhook_url=${{ secrets.SLACK_WEBHOOK_URL }}" -var="github_token=${{ secrets.GITHUB_TOKEN_DRIFT }}"